- name: Check Windows Updates
  hosts: windows
  vars:
    win_update_category_names:
      - CriticalUpdates
      - DefinitionUpdates
      - SecurityUpdates
      - UpdateRollups
      - Updates

  roles:
    - check_updates