- hosts: all
  import_playbook: check_updates.yml
 # roles:
 #   - role: get_token
 #   - role: create_maintenance
 #     when: OPERATION == 'CREATE'
 #   - role: delete_maintenance
 #     when: OPERATION == 'DELETE'